// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionFormController from "./accordion_form_controller"
application.register("accordion-form", AccordionFormController)

import PatronRequestController from "./patron_request_controller"
application.register("patron-request", PatronRequestController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import ItemSelectorController from "./item_selector_controller"
application.register("item-selector", ItemSelectorController)

import TableController from "./table_controller"
application.register("table", TableController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import MediationController from "./mediation_controller"
application.register("mediation", MediationController)

import FormController from "./form_controller"
application.register("form", FormController)

import RememberController from "./remember_controller"
application.register("remember", RememberController)

import ArchivesSeriesController from "./archives_series_controller"
application.register("archives-series", ArchivesSeriesController)

import AppointmentController from "./appointment_controller"
application.register("appointment", AppointmentController)
import ArchivesRequestController from "./archives_request_controller"
application.register("archives-request", ArchivesRequestController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SelectedItemFormController from "./selected_item_form_controller"
application.register("selected-item-form", SelectedItemFormController)
