// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionFormController from "./accordion_form_controller"
application.register("accordion-form", AccordionFormController)

import PatronRequestController from "./patron_request_controller"
application.register("patron-request", PatronRequestController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import ItemSelectorController from "./item_selector_controller"
application.register("item-selector", ItemSelectorController)

import TableController from "./table_controller"
application.register("table", TableController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import MediationController from "./mediation_controller"
application.register("mediation", MediationController)

import FormController from "./form_controller"
application.register("form", FormController)

import RememberController from "./remember_controller"
application.register("remember", RememberController)

import AeonConfirmationPollController from "./aeon_confirmation_poll_controller"
application.register("aeon-confirmation-poll", AeonConfirmationPollController)

import ArchivesSeriesController from "./archives_series_controller"
application.register("archives-series", ArchivesSeriesController)

import AppointmentController from "./appointment_controller"
application.register("appointment", AppointmentController)

import AppointmentSelectController from "./appointment_select_controller"
application.register("appointment-select", AppointmentSelectController)

import OtpInput from "./otp_input_controller"
application.register("otp-input", OtpInput)

import ProgressBarController from "./progress_bar_controller"
application.register("progress-bar", ProgressBarController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SaveForLaterController from "./save_for_later_controller"
application.register("save-for-later", SaveForLaterController)

import SelectedItemFormController from "./selected_item_form_controller"
application.register("selected-item-form", SelectedItemFormController)

import StatusCounterController from "./status_counter_controller"
application.register("status-counter", StatusCounterController)

import EmptyRemoveController from "./empty_remove_controller"
application.register("empty-remove", EmptyRemoveController)

import DraftRequestController from "./draft_request_controller"
application.register("draft-request", DraftRequestController)

import CharCounterController from "./char_counter_controller"
application.register("char-counter", CharCounterController)

import EadSearchController from "./ead_search_controller"
application.register("ead-search", EadSearchController)

import ViewContainerContentsController from "./view_container_contents_controller"
application.register("view-container-contents", ViewContainerContentsController)

import AddItemsController from "./add_items_controller"
application.register("add-items", AddItemsController)
