linter:
  enabled: true
  rules:
    erb-no-instance-variables-in-partials:
      enabled: false
    html-require-script-nonce:
      enabled: false
    erb-no-duplicate-branch-elements:
      enabled: false
    html-no-aria-hidden-on-focusable:
      enabled: false
