require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Layout/LineLength:
  Max: 125
  Exclude:
    - 'spec/mailers/approval_status_mailer_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/request_spec.rb'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'app/models/request.rb'
    - 'app/controllers/requests_controller.rb'

Metrics/ModuleLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
