inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/ModuleLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
