plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "spec/spec_helper.rb"
    - "vendor/**/*"
  TargetRubyVersion: 4.0
  NewCops: enable

Rails:
  Enabled: true

Layout/LineLength:
  Max: 140
  Exclude:
    - "spec/mailers/approval_status_mailer_spec.rb"

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/models/request_spec.rb"
    - "spec/factories/**/*"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "app/services/symphony_client.rb"

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - "app/helpers/requests_helper.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 20

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
