scss_files: 'app/assets/**/*.scss'

exclude: 'vendor/**'

linters:
  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero

  NestingDepth:
    enabled: true
    max_depth: 5

  # We sometimes need to extend bootstrap classes
  # but we don't have placeholder classes for them
  PlaceholderInExtend:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 5

  # Ignoring particular selectors from format
  # linting since they are out of our control
  SelectorFormat:
    ignored_names:
      - noncirc_page

  StringQuotes:
    enabled: true
    style: single_quotes

  VendorPrefix:
    enabled: false
