scss_files: 'app/assets/**/*.scss'

exclude: 'vendor/**'

linters:
  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero

  NestingDepth:
    enabled: true
    max_depth: 5

  SelectorDepth:
    enabled: true
    max_depth: 5

  StringQuotes:
    enabled: true
    style: single_quotes

  VendorPrefix:
    enabled: false
