dist: bionic
notifications:
  email: false

rvm:
  - 2.7.0

addons:
  chrome: stable

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=54ad400aa6bd7b806417ac419c66d85a9ea5ea342c7408283bdba7afa91ea996

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

sudo: false
language: ruby

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
