dist: xenial
notifications:
  email: false

rvm:
  - 2.6.3

addons:
  chrome: stable

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem update --system
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

sudo: false
language: ruby
