# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a04476e55523d6b6f4368683177bb936ce8acb3fc7e24653f1555e4adca7e8ec0b93e590253775bc59886cec9539b38f5c52687597928aec8a25aa184a47dd49

test:
  secret_key_base: a2e43f5f3c92191a5230d5c985f11d345502d71114af569f0b9bd787d9b2712f16c944c8f4258a5730629d0e8ee951893ff08f1adc80c4f6d5048d5f5d4f691f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
