# nodoc: Autogenerated
module ApplicationHelper
  def dialog_column_class
    'col-md-6 col-md-offset-3'
  end

  def bootstrap_form_layout_options
    { layout: :horizontal, label_col: label_column_class, control_col: content_column_class }
  end

  def label_column_class
    'col-xs-2'
  end

  def content_column_class
    'col-xs-10'
  end
end
