# This is different on any server running under development
token_encrypt:
  secret: 'OpCeOjbiQUwyyzoMzjtHnGbgfOthajiUqwbQuXNZRitkkQpvMPHILfcmkvikFcaN'
  salt: 'dcVNcekAYNIFtggdJXQpSkWHBpBVsVsPiRzCFpWbZGLrQtHKSdMBKIWKmYYIZnkbXuMisFlSkHbUmIimKMbjFMVDpfzyIRLvmLYBUparuPAaxYjPzdmFfRGBGgxfvwOR'

mailer_host: 'localhost:3000'
